configs:
  params:
    server.insecure: true
    server.basehref: "/argocd"
    server.rootpath: "/argocd"

server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: azure/application-gateway
      nginx.ingress.kubernetes.io/ssl-redirect: "false"

    hosts: [crqrswo.francecentral.cloudapp.azure.com]
    paths: [/argocd]
