apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-metrics" (include "node-app-chart.fullname" .) }}
  labels:
    {{- include "node-app-chart.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.metricsPort }}
      targetPort: 8080
      protocol: TCP
      name: metrics-http
  selector:
    {{- include "node-app-chart.selectorLabels" . | nindent 4 }}
