provisionDataStore:
  elasticsearch: true
  cassandra: false

storage:
  type: elasticsearch

elasticsearch:
  replicas: 1
  clusterHealthCheckParams: wait_for_status=yellow&timeout=50s

query:
  basePath: "/jaeger"
