name: Validate, build & Deploy

on:
  push:
    branches:
      - master
    paths:
      - "services"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - folder: "services/apps/api-gateway"
            name: api-gateway
          - folder: "services/apps/order"
            name: order
          - folder: "services/apps/payment"
            name: payment

        name:
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        working-directory: ${{ matrix.service.folder }}
        with:
          push: true
          tags:
            - wadhah101/${{ matrix.service.name }}:latest
            - wadhah101/${{ matrix.service.name }}:${{ github.sha }}
