name: Build and push services

on:
  push:
    branches:
      - master
    paths:
      - "services"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - folder: "apps/api-gateway"
            name: api-gateway
          - folder: "apps/order"
            name: order
          - folder: "apps/payment"
            name: payment
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          cache-from: "wadhah101/${{ matrix.service.name }}:latest"
          file: ${{ matrix.service.folder }}/Dockerfile
          context: "{{defaultContext}}:services"
          push: true
          tags: |
            wadhah101/${{ matrix.service.name }}:latest
            wadhah101/${{ matrix.service.name }}:${{ github.sha }}
